"""make organization plan_id nullable

Revision ID: 2d612e09d0ed
Revises: 27b96fffe577
Create Date: 2026-09-11 11:44:37.265882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d612e09d0ed'
down_revision: Union[str, Sequence[str], None] = '27b96fffe577'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('organizations', 'plan_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('organizations', 'plan_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
