"""rename ticket_list to ticket_limit in plans

Revision ID: 4bb428793750
Revises: e710c6c1f3cf
Create Date: 2026-09-28 16:46:28.685048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bb428793750'
down_revision: Union[str, Sequence[str], None] = 'e710c6c1f3cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plans', sa.Column('ticket_limit', sa.Integer(), nullable=False))
    op.drop_column('plans', 'ticket_list')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plans', sa.Column('ticket_list', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('plans', 'ticket_limit')
    # ### end Alembic commands ###
