"""add is_escalated to tickets

Revision ID: e7d63a6dcb9f
Revises: 4bb428793750
Create Date: 2026-09-30 11:01:31.003107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7d63a6dcb9f'
down_revision: Union[str, Sequence[str], None] = '4bb428793750'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('is_escalated', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'is_escalated')
    # ### end Alembic commands ###
